# Generated by Django 2.2.5 on 2021-02-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210217_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.CharField(blank=True, choices=[('books', 'Books'), ('movies', 'Movies')], max_length=10, null=True),
        ),
    ]
